Update build-openwrt-with-imagebuilder.yml

diff --git a/.github/workflows/build-openwrt-with-imagebuilder.yml b/.github/workflows/build-openwrt-with-imagebuilder.yml
--- a/.github/workflows/build-openwrt-with-imagebuilder.yml
+++ b/.github/workflows/build-openwrt-with-imagebuilder.yml
@@ -25,144 +25,7 @@ on:
           - s905x3-x88-pro-x3_s912-m8s-pro_s905x-t95_s912-t95z-plus_s905l3-unt400g1_s905lb-r3300l
           - tanix-tx6_tb-ls3399_tn3399_tpm312_tqc-a01_tvi3315a_vplus_xiaobao_zcube1-max_zk-r39a_zysj
           - vplus_tanix-tx6_tqc-a01
-          - a311d
-          - beikeyun
-          - chainedbox
-          - crrc
-          - dg3399
-          - dlfr100
-          - e20c
-          - e25
-          - eaidk-610
-          - emb3531
-          - fine3399
-          - firefly-rk3399
-          - jp-tvbox
-          - h28k
-          - h66k
-          - h68k
-          - h69k
-          - h88k
-          - h88k-v3
-          - h96-max-m2
-          - hs530r
-          - hugsun-x99
-          - ipc-r
-          - king3399
-          - kylin3399
-          - leez
-          - lx-r3s
-          - mrkaio-m68s
-          - nanopc-t6
-          - nanopi-r5c
-          - nanopi-r5s
-          - orangepi-5-plus
-          - panther-x2
-          - r66s
-          - r68s
-          - renegade-rk3328
-          - rk3318-box
-          - rock5b
-          - rock5c
-          - ruisen-box
-          - s905
-          - s905-beelink-mini
-          - s905-mxqpro-plus
-          - s905d
-          - s905d-ki-pro
-          - s905d-sml5442tw
-          - s905l
-          - s905l-aurora-1s
-          - s905l-mg101
-          - s905l2
-          - s905l2-e900v21e
-          - s905l2-wojia
-          - s905l3
-          - s905l3-cm211
-          - s905l3-unt400g1
-          - s905l3-unt402a
-          - s905l3a
-          - s905l3a-cm311
-          - s905l3a-m401a
-          - s905l3b
-          - s905l3b-e900v21d
-          - s905l3b-e900v22d
-          - s905l3b-e900v22e
-          - s905l3b-ip103h
-          - s905l3b-rg020et-ca
-          - s905l3b-unt403a
-          - s905lb-ipbs9505
-          - s905lb-q96-mini
-          - s905lb-r3300l
-          - s905mb
-          - s905w
-          - s905w-w95
-          - s905w-x96-mini
-          - s905w-x96w
-          - s905x
-          - s905x-b860h
-          - s905x-nexbox-a95x
-          - s905x-t95
-          - s905x-tbee
-          - s905x-tx9
-          - s905x2
-          - s905x2-km3
-          - s905x2-x96max-2g
-          - s905x3
-          - s905x3-2101
-          - s905x3-a100
-          - s905x3-a95xf3
-          - s905x3-a95xf3-gb
-          - s905x3-b
-          - s905x3-h96max
-          - s905x3-hk1
-          - s905x3-ip1001m
-          - s905x3-q1
-          - s905x3-q2
-          - s905x3-tx3
-          - s905x3-tx3-bz
-          - s905x3-ugoosx3
-          - s905x3-whale
-          - s905x3-x88-pro-x3
-          - s905x3-x96air
-          - s905x3-x96air-gb
-          - s905x3-x96max
-          - s912
-          - s912-h96pro-plus
-          - s912-m8s-pro
-          - s912-nexbox-a1
-          - s912-nexbox-a2
-          - s912-onecloudpro
-          - s912-phicomm-t1
-          - s912-t95z-plus
-          - s912-tx8-max
-          - s912-tx9-pro-2g
-          - s912-tx9-pro-3g
-          - s912-x92
-          - s912-zyxq-fake
-          - s922x
-          - s922x-ct2000
-          - s922x-gtking
-          - s922x-gtkingpro-h
-          - s922x-odroid-n2
-          - s922x-reva
-          - s922x-ugoos-am6
-          - seewo-sv21
           - smart-am40
-          - station-m1
-          - swan1-w28
-          - sw799
-          - tanix-tx6
-          - tb-ls3399
-          - tn3399
-          - tpm312
-          - tqc-a01
-          - tvi3315a
-          - vplus
-          - xiaobao
-          - zcube1-max
-          - zk-r39a
-          - zysj
       openwrt_kernel:
         description: "Select kernel version"
         required: false
@@ -271,25 +134,14 @@ jobs:
           echo "RELEASES_TAG=${RELEASES_BRANCH/:/_}" >> ${GITHUB_ENV}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Clear server space and prepare for kernel build
+      - name: Debug OpenWrt Rootfs
         if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
         run: |
-          cd imagebuilder
-          rm -rf $(ls . | grep -v "^bin$" | xargs) 2>/dev/null
+          echo "Contents of imagebuilder directory:"
+          ls -R imagebuilder
+          echo "Contents of /builder directory:"
+          sudo ls -R /builder
 
-          # Create the openwrt directory in /builder
-          sudo mkdir -p /builder/openwrt
-          sudo chown -R runner:runner /builder/openwrt
-
-          # Create a symbolic link
-          ln -sf /builder/openwrt /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-openwrt/main/openwrt
-
-          # Display the file system status
-          df -hT ${PWD}
-          
-          # List the contents of the openwrt directory
-          ls -la /builder/openwrt
-          
       - name: Prepare OpenWrt rootfs
         if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
         run: |
@@ -297,8 +149,15 @@ jobs:
           sudo mkdir -p /builder/openwrt/bin/targets/armvirt/64
           sudo chown -R runner:runner /builder/openwrt
 
-          # 复制 imagebuilder 生成的文件到正确的位置
-          sudo cp -v imagebuilder/bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz /builder/openwrt/bin/targets/armvirt/64/
+          # 查找 rootfs 文件
+          ROOTFS_FILE=$(find imagebuilder -name "*rootfs.tar.gz" | head -n 1)
+          if [ -z "$ROOTFS_FILE" ]; then
+            echo "Error: rootfs file not found"
+            exit 1
+          fi
+
+          # 复制找到的 rootfs 文件到正确的位置
+          sudo cp -v "$ROOTFS_FILE" /builder/openwrt/bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz
 
           # 显示文件内容
           ls -la /builder/openwrt/bin/targets/armvirt/64/
@@ -308,7 +167,7 @@ jobs:
 
           # 显示符号链接
           ls -la /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-openwrt/main/
-          
+
       - name: Build OpenWrt firmware
         if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
         uses: kemp-zz/amlogic-s9xxx-openwrt@main
@@ -322,10 +181,10 @@ jobs:
           builder_name: ${{ inputs.builder_name }}
         env:
           GITHUB_WORKSPACE: ${{ github.workspace }}
-          OPENWRT_ARMVIRT: immortalwrt-23.05.3-armsr-armv8-generic-rootfs.tar.gz
+          OPENWRT_ARMVIRT: /builder/openwrt/bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz
 
       - name: Debug information
-        if: always()
+        if: failure()
         run: |
           echo "Current directory: $(pwd)"
           echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
@@ -333,12 +192,8 @@ jobs:
           ls -la $GITHUB_WORKSPACE
           echo "Contents of /builder/openwrt:"
           ls -la /builder/openwrt
-          echo "Contents of /builder/openwrt/bin/targets/armsr/armv8:"
-          ls -la /builder/openwrt/bin/targets/armsr/armv8
           echo "Contents of /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-openwrt/main:"
           ls -la /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-openwrt/main
-          echo "Contents of /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-openwrt/main/openwrt/bin/targets/armsr/armv8:"
-          ls -la /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-openwrt/main/openwrt/bin/targets/armsr/armv8
 
       - name: Upload the packaged OpenWrt
         uses: ncipollo/release-action@main
